# .github/workflows/sql-deploy.yml
name: Update SQL database
on:
  push:
    branches: 
      - main

jobs:
  deploySQLSatDenmarkDB:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    # find out which directory initially in
    - name: find location
      run: |
        ls
    # call sqlpackage.exe to deploy my db schema using my dacpac
    - name: update database schema using dacpac
      run: |
        cd 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150'
        ./sqlpackage.exe /Action:Publish /SourceFile:"D:\Published artifacts\Database\UnitTesting-Data.dacpac" /TargetConnectionString:"${{ secrets.PROD_SQL_CONNECTION_STRING }}" /p:BlockOnPossibleDataLoss=False /d